/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cursoliferay.recetasdelmundo.sb.model.impl;

import com.cursoliferay.recetasdelmundo.sb.model.Instruccion;
import com.cursoliferay.recetasdelmundo.sb.model.InstruccionModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Instruccion service. Represents a row in the &quot;RDM_Instruccion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>InstruccionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link InstruccionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InstruccionImpl
 * @generated
 */
public class InstruccionModelImpl
	extends BaseModelImpl<Instruccion> implements InstruccionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a instruccion model instance should use the <code>Instruccion</code> interface instead.
	 */
	public static final String TABLE_NAME = "RDM_Instruccion";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"instruccionId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"descripcion", Types.VARCHAR}, {"recetaId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("instruccionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("descripcion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("recetaId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table RDM_Instruccion (uuid_ VARCHAR(75) null,instruccionId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,descripcion VARCHAR(75) null,recetaId LONG)";

	public static final String TABLE_SQL_DROP = "drop table RDM_Instruccion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY instruccion.instruccionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY RDM_Instruccion.instruccionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long RECETAID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INSTRUCCIONID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public InstruccionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _instruccionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setInstruccionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _instruccionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Instruccion.class;
	}

	@Override
	public String getModelClassName() {
		return Instruccion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Instruccion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Instruccion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Instruccion, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Instruccion)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Instruccion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Instruccion, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Instruccion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Instruccion, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Instruccion, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Instruccion>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Instruccion.class.getClassLoader(), Instruccion.class,
			ModelWrapper.class);

		try {
			Constructor<Instruccion> constructor =
				(Constructor<Instruccion>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Instruccion, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Instruccion, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Instruccion, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Instruccion, Object>>();
		Map<String, BiConsumer<Instruccion, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Instruccion, ?>>();

		attributeGetterFunctions.put("uuid", Instruccion::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Instruccion, String>)Instruccion::setUuid);
		attributeGetterFunctions.put(
			"instruccionId", Instruccion::getInstruccionId);
		attributeSetterBiConsumers.put(
			"instruccionId",
			(BiConsumer<Instruccion, Long>)Instruccion::setInstruccionId);
		attributeGetterFunctions.put("companyId", Instruccion::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Instruccion, Long>)Instruccion::setCompanyId);
		attributeGetterFunctions.put("groupId", Instruccion::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Instruccion, Long>)Instruccion::setGroupId);
		attributeGetterFunctions.put("userId", Instruccion::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Instruccion, Long>)Instruccion::setUserId);
		attributeGetterFunctions.put("userName", Instruccion::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Instruccion, String>)Instruccion::setUserName);
		attributeGetterFunctions.put("createDate", Instruccion::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Instruccion, Date>)Instruccion::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Instruccion::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Instruccion, Date>)Instruccion::setModifiedDate);
		attributeGetterFunctions.put(
			"descripcion", Instruccion::getDescripcion);
		attributeSetterBiConsumers.put(
			"descripcion",
			(BiConsumer<Instruccion, String>)Instruccion::setDescripcion);
		attributeGetterFunctions.put("recetaId", Instruccion::getRecetaId);
		attributeSetterBiConsumers.put(
			"recetaId",
			(BiConsumer<Instruccion, Long>)Instruccion::setRecetaId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getInstruccionId() {
		return _instruccionId;
	}

	@Override
	public void setInstruccionId(long instruccionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_instruccionId = instruccionId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getDescripcion() {
		if (_descripcion == null) {
			return "";
		}
		else {
			return _descripcion;
		}
	}

	@Override
	public void setDescripcion(String descripcion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descripcion = descripcion;
	}

	@Override
	public long getRecetaId() {
		return _recetaId;
	}

	@Override
	public void setRecetaId(long recetaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_recetaId = recetaId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalRecetaId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("recetaId"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Instruccion.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Instruccion.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Instruccion toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Instruccion>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		InstruccionImpl instruccionImpl = new InstruccionImpl();

		instruccionImpl.setUuid(getUuid());
		instruccionImpl.setInstruccionId(getInstruccionId());
		instruccionImpl.setCompanyId(getCompanyId());
		instruccionImpl.setGroupId(getGroupId());
		instruccionImpl.setUserId(getUserId());
		instruccionImpl.setUserName(getUserName());
		instruccionImpl.setCreateDate(getCreateDate());
		instruccionImpl.setModifiedDate(getModifiedDate());
		instruccionImpl.setDescripcion(getDescripcion());
		instruccionImpl.setRecetaId(getRecetaId());

		instruccionImpl.resetOriginalValues();

		return instruccionImpl;
	}

	@Override
	public Instruccion cloneWithOriginalValues() {
		InstruccionImpl instruccionImpl = new InstruccionImpl();

		instruccionImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		instruccionImpl.setInstruccionId(
			this.<Long>getColumnOriginalValue("instruccionId"));
		instruccionImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		instruccionImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		instruccionImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		instruccionImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		instruccionImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		instruccionImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		instruccionImpl.setDescripcion(
			this.<String>getColumnOriginalValue("descripcion"));
		instruccionImpl.setRecetaId(
			this.<Long>getColumnOriginalValue("recetaId"));

		return instruccionImpl;
	}

	@Override
	public int compareTo(Instruccion instruccion) {
		long primaryKey = instruccion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Instruccion)) {
			return false;
		}

		Instruccion instruccion = (Instruccion)object;

		long primaryKey = instruccion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Instruccion> toCacheModel() {
		InstruccionCacheModel instruccionCacheModel =
			new InstruccionCacheModel();

		instruccionCacheModel.uuid = getUuid();

		String uuid = instruccionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			instruccionCacheModel.uuid = null;
		}

		instruccionCacheModel.instruccionId = getInstruccionId();

		instruccionCacheModel.companyId = getCompanyId();

		instruccionCacheModel.groupId = getGroupId();

		instruccionCacheModel.userId = getUserId();

		instruccionCacheModel.userName = getUserName();

		String userName = instruccionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			instruccionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			instruccionCacheModel.createDate = createDate.getTime();
		}
		else {
			instruccionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			instruccionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			instruccionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		instruccionCacheModel.descripcion = getDescripcion();

		String descripcion = instruccionCacheModel.descripcion;

		if ((descripcion != null) && (descripcion.length() == 0)) {
			instruccionCacheModel.descripcion = null;
		}

		instruccionCacheModel.recetaId = getRecetaId();

		return instruccionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Instruccion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Instruccion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Instruccion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Instruccion)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Instruccion, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Instruccion, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Instruccion, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Instruccion)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Instruccion>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _instruccionId;
	private long _companyId;
	private long _groupId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _descripcion;
	private long _recetaId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Instruccion, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Instruccion)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("instruccionId", _instruccionId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("descripcion", _descripcion);
		_columnOriginalValues.put("recetaId", _recetaId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("instruccionId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("groupId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("descripcion", 256L);

		columnBitmasks.put("recetaId", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Instruccion _escapedModel;

}