/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.cursoliferay.recetasdelmundo.sb.model.impl;

import com.cursoliferay.recetasdelmundo.sb.model.Receta;
import com.cursoliferay.recetasdelmundo.sb.service.RecetaLocalServiceUtil;

/**
 * The extended model base implementation for the Receta service. Represents a row in the &quot;RDM_Receta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RecetaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RecetaImpl
 * @see Receta
 * @generated
 */
public abstract class RecetaBaseImpl extends RecetaModelImpl implements Receta {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a receta model instance should use the <code>Receta</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			RecetaLocalServiceUtil.addReceta(this);
		}
		else {
			RecetaLocalServiceUtil.updateReceta(this);
		}
	}

}